// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.Data;

#nullable disable

namespace StudentManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagement.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StudentFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StudentLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StudentFirstName = "John",
                            StudentLastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            StudentFirstName = "Anna",
                            StudentLastName = "Brown"
                        },
                        new
                        {
                            Id = 3,
                            StudentFirstName = "Michael",
                            StudentLastName = "Johnson"
                        },
                        new
                        {
                            Id = 4,
                            StudentFirstName = "Emily",
                            StudentLastName = "Davis"
                        },
                        new
                        {
                            Id = 5,
                            StudentFirstName = "David",
                            StudentLastName = "Wilson"
                        },
                        new
                        {
                            Id = 6,
                            StudentFirstName = "Sophia",
                            StudentLastName = "Miller"
                        },
                        new
                        {
                            Id = 7,
                            StudentFirstName = "Daniel",
                            StudentLastName = "Moore"
                        },
                        new
                        {
                            Id = 8,
                            StudentFirstName = "Olivia",
                            StudentLastName = "Taylor"
                        },
                        new
                        {
                            Id = 9,
                            StudentFirstName = "James",
                            StudentLastName = "Anderson"
                        },
                        new
                        {
                            Id = 10,
                            StudentFirstName = "Emma",
                            StudentLastName = "Thomas"
                        });
                });

            modelBuilder.Entity("StudentManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserLogin")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserLogin = "admin",
                            UserPassword = "AQAAAAIAAYagAAAAEJy80kguewONZOfDnVVVRH3r9bk9t9WXeuRMNVndPcd1gMrtdlcpMtvK+C7KRlas5w=="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
